[package]
name = "geom"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
aabb-quadtree = "0.1.0"
abstutil = { path = "../abstutil" }
earcutr = { git = "https://github.com/dabreegster/earcutr", branch = "patch-1" }
geo = "0.15.0"
geo-booleanop = "= 0.3.2"
histogram = "0.6.9"
instant = "0.1.7"
ordered-float = { version = "2.0.0", features=["serde"] }
polylabel = "2.3.1"
serde = "1.0.116"
